### ISSUE TITLE
V 0.0.1

### ISSUE THREAD

**Issue by machinecode1** [treekiller12/Development_-Filman_TV#3]
O wiele lepszy wygląd. Wyszukiwarka pięknie wszystko znajduje. W kategoriach znacznie lepiej widać gdzie się jest, i ogólnie mam wrażenie że jakoś lepiej się porusza pilotem po pozycjach.
 Jednym słowem...brawo!!!

**Comment by machinecode1** [comment]
V 0.0.2-  ogromna poprawa playera!! Problem z paskiem nie występuje, znika wszystko samo!
Nie wiem czy mam co jeszcze dodać prócz tego co wymieniłeś odnośnie playera...może tylko do pełni szczęścia brakuje przewijania strzałkami,ale to nie jest rzecz bez której nie da się żyć. Niesamowita robota i to jeszcze w tak krótkim czasie🥃🥃

**Comment by treekiller12** [comment]
jedank się trochę opóźni
